import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier/flat";

const eslintConfig = defineConfig([
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "coverage/**",
    "playwright-report/**",
    "test-results/**",
    "next-env.d.ts",
    // Generated by `convex dev` — never hand-edited, never linted.
    "convex/_generated/**",
  ]),
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // Unused vars are an error, except deliberate `_`-prefixed placeholders.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // Locale-aware navigation only: `next/link` and `next/navigation` drop
      // the active locale and silently break every non-English route.
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "next/link",
              message: "Import { Link } from '@/i18n/navigation' instead.",
            },
            {
              name: "next/navigation",
              importNames: ["redirect", "usePathname", "useRouter"],
              message:
                "Import locale-aware helpers from '@/i18n/navigation' instead.",
            },
          ],
        },
      ],
    },
  },
  {
    // The i18n layer is what wraps those APIs, so it must be able to use them.
    files: ["src/i18n/**", "src/proxy.ts", "src/app/**/layout.tsx"],
    rules: { "no-restricted-imports": "off" },
  },
  // Must stay last: turns off every stylistic rule Prettier owns.
  prettier,
]);

export default eslintConfig;
