import type { Locale } from "../../src/i18n/locales";

/**
 * Luma.Green's material codes — the catalogue every screen, price and trade
 * uses. Edit this file to add or rename a material, then re-run the seed
 * (`npx convex run demo:reset`). Names are per language; anything missing
 * falls back to English.
 *
 * Prices are Bengaluru SAMPLE figures for the prototype (paise per kg), not
 * market data. CO2e factors are indicative (kg CO2e avoided per kg recycled
 * instead of made new), rounded from published averages such as the US EPA
 * WARM model — replace them with sourced factors before any public claim.
 */

export type Family =
  "paper" | "plastic" | "metal" | "glass" | "ewaste" | "other";

export interface CatalogueEntry {
  code: string;
  family: Family;
  /** Scrap is bought from households; recycled output is sold to factories. */
  stage: "scrap" | "recycled";
  names: Record<Locale, string>;
  /** Bengaluru sample prices, paise per kg: the admin floor and fallback. */
  floorPaise: number;
  fallbackPaise: number;
  co2eFactor: number;
}

export const CATALOGUE: readonly CatalogueEntry[] = [
  {
    code: "PAPER-NEWS",
    family: "paper",
    stage: "scrap",
    names: {
      en: "Newspaper",
      hi: "अख़बार (रद्दी)",
      kn: "ದಿನಪತ್ರಿಕೆ (ರದ್ದಿ)",
      bn: "খবরের কাগজ",
      mr: "वर्तमानपत्र",
      ta: "செய்தித்தாள்",
      te: "వార్తాపత్రిక",
      ml: "പത്രം",
      gu: "અખબાર",
      pa: "ਅਖ਼ਬਾਰ",
      ur: "اخبار",
      ar: "صحف",
      as: "বাতৰিকাকত",
      ne: "पत्रिका",
      es: "Periódicos",
      fr: "Journaux",
      vi: "Giấy báo",
      si: "පුවත්පත්",
      th: "หนังสือพิมพ์",
      ru: "Газеты",
      de: "Zeitungen",
      or: "ଖବରକାଗଜ",
      ja: "新聞紙",
      uk: "Газети",
      ko: "신문지",
      it: "Giornali",
      pl: "Gazety",
      tr: "Gazete",
      zh: "报纸",
      pt: "Jornais",
      id: "Koran",
      nl: "Kranten",
      ms: "Surat khabar",
    },
    floorPaise: 1200,
    fallbackPaise: 1400,
    co2eFactor: 1,
  },
  {
    code: "PAPER-CARTON",
    family: "paper",
    stage: "scrap",
    names: {
      en: "Cardboard boxes",
      hi: "गत्ता",
      kn: "ರಟ್ಟು ಡಬ್ಬಗಳು",
      bn: "কার্ডবোর্ডের বাক্স",
      mr: "पुठ्ठ्याचे खोके",
      ta: "அட்டைப் பெட்டிகள்",
      te: "అట్టపెట్టెలు",
      ml: "കാർഡ്ബോർഡ് പെട്ടികൾ",
      gu: "પૂંઠાનાં બોક્સ",
      pa: "ਗੱਤੇ ਦੇ ਡੱਬੇ",
      ur: "گتے کے ڈبے",
      ar: "صناديق كرتونية",
      as: "কাৰ্ডব'ৰ্ডৰ বাকচ",
      ne: "कार्टनका बाकस",
      es: "Cajas de cartón",
      fr: "Boîtes en carton",
      vi: "Thùng bìa carton",
      si: "කාඩ්බෝඩ් පෙට්ටි",
      th: "กล่องกระดาษลูกฟูก",
      ru: "Картонные коробки",
      de: "Kartonverpackungen",
      or: "କାର୍ଡବୋର୍ଡ ବାକ୍ସ",
      ja: "段ボール箱",
      uk: "Картонні коробки",
      ko: "골판지 상자",
      it: "Scatole di cartone",
      pl: "Karton i tektura",
      tr: "Karton kutular",
      zh: "纸箱",
      pt: "Caixas de papelão",
      id: "Kardus",
      nl: "Kartonnen dozen",
      ms: "Kotak kadbod",
    },
    floorPaise: 800,
    fallbackPaise: 1000,
    co2eFactor: 1,
  },
  {
    code: "PAPER-BOOKS",
    family: "paper",
    stage: "scrap",
    names: {
      en: "Books and notebooks",
      hi: "किताबें और कॉपियाँ",
      kn: "ಪುಸ್ತಕ ಮತ್ತು ನೋಟ್‌ಬುಕ್",
      bn: "বই ও খাতা",
      mr: "पुस्तके आणि वह्या",
      ta: "புத்தகங்கள் மற்றும் குறிப்பேடுகள்",
      te: "పుస్తకాలు మరియు నోటుపుస్తకాలు",
      ml: "പുസ്തകങ്ങളും നോട്ടുപുസ്തകങ്ങളും",
      gu: "પુસ્તકો અને નોટબુક",
      pa: "ਕਿਤਾਬਾਂ ਅਤੇ ਕਾਪੀਆਂ",
      ur: "کتابیں اور کاپیاں",
      ar: "كتب ودفاتر",
      as: "কিতাপ আৰু বহী",
      ne: "किताब र कापी",
      es: "Libros y cuadernos",
      fr: "Livres et cahiers",
      vi: "Sách và vở",
      si: "පොත් සහ සටහන් පොත්",
      th: "หนังสือและสมุด",
      ru: "Книги и тетради",
      de: "Bücher und Hefte",
      or: "ବହି ଓ ଖାତା",
      ja: "本・ノート",
      uk: "Книжки й зошити",
      ko: "책과 공책",
      it: "Libri e quaderni",
      pl: "Książki i zeszyty",
      tr: "Kitap ve defterler",
      zh: "书籍和笔记本",
      pt: "Livros e cadernos",
      id: "Buku dan buku tulis",
      nl: "Boeken en schriften",
      ms: "Buku dan buku nota",
    },
    floorPaise: 1000,
    fallbackPaise: 1200,
    co2eFactor: 1,
  },
  {
    code: "PAPER-OFFICE",
    family: "paper",
    stage: "scrap",
    names: {
      en: "White office paper",
      hi: "सफ़ेद कागज़",
      kn: "ಬಿಳಿ ಕಾಗದ",
      bn: "অফিসের সাদা কাগজ",
      mr: "कार्यालयातील पांढरा कागद",
      ta: "அலுவலக வெள்ளைக் காகிதம்",
      te: "కార్యాలయ తెల్ల కాగితం",
      ml: "ഓഫീസിലെ വെളുത്ത കടലാസ്",
      gu: "ઓફિસનો સફેદ કાગળ",
      pa: "ਦਫ਼ਤਰ ਦਾ ਚਿੱਟਾ ਕਾਗਜ਼",
      ur: "دفتر کا سفید کاغذ",
      ar: "ورق مكتبي أبيض",
      as: "কাৰ্যালয়ৰ বগা কাগজ",
      ne: "सेतो कार्यालय कागज",
      es: "Papel blanco de oficina",
      fr: "Papier de bureau blanc",
      vi: "Giấy văn phòng trắng",
      si: "සුදු කාර්යාල කඩදාසි",
      th: "กระดาษสำนักงานสีขาว",
      ru: "Белая офисная бумага",
      de: "Weißes Büropapier",
      or: "କାର୍ଯ୍ୟାଳୟର ଧଳା କାଗଜ",
      ja: "白い事務用紙",
      uk: "Білий офісний папір",
      ko: "흰 사무용지",
      it: "Carta bianca da ufficio",
      pl: "Biały papier biurowy",
      tr: "Beyaz ofis kâğıdı",
      zh: "白色办公用纸",
      pt: "Papel branco de escritório",
      id: "Kertas kantor putih",
      nl: "Wit kantoorpapier",
      ms: "Kertas pejabat putih",
    },
    floorPaise: 1400,
    fallbackPaise: 1600,
    co2eFactor: 1,
  },
  {
    code: "PAPER-MIXED",
    family: "paper",
    stage: "scrap",
    names: {
      en: "Mixed paper",
      hi: "मिक्स कागज़",
      kn: "ಮಿಶ್ರ ಕಾಗದ",
      bn: "মিশ্র কাগজ",
      mr: "मिश्र कागद",
      ta: "கலப்புக் காகிதம்",
      te: "మిశ్రమ కాగితం",
      ml: "മിശ്രിത കടലാസ്",
      gu: "મિશ્ર કાગળ",
      pa: "ਮਿਲਿਆ-ਜੁਲਿਆ ਕਾਗਜ਼",
      ur: "ملا جلا کاغذ",
      ar: "ورق مختلط",
      as: "মিশ্ৰ কাগজ",
      ne: "मिसिएको कागज",
      es: "Papel mezclado",
      fr: "Papiers mélangés",
      vi: "Giấy hỗn hợp",
      si: "මිශ්‍ර කඩදාසි",
      th: "กระดาษคละชนิด",
      ru: "Смешанная бумага",
      de: "Mischpapier",
      or: "ମିଶ୍ରିତ କାଗଜ",
      ja: "混合紙",
      uk: "Змішаний папір",
      ko: "혼합 종이",
      it: "Carta mista",
      pl: "Papier mieszany",
      tr: "Karışık kâğıt",
      zh: "混合纸",
      pt: "Papel misto",
      id: "Kertas campuran",
      nl: "Gemengd papier",
      ms: "Kertas bercampur",
    },
    floorPaise: 600,
    fallbackPaise: 800,
    co2eFactor: 1,
  },
  {
    code: "PLASTIC-PET",
    family: "plastic",
    stage: "scrap",
    names: {
      en: "PET bottles",
      hi: "पेट बोतलें",
      kn: "ಪೆಟ್ ಬಾಟಲಿ",
      bn: "PET বোতল",
      mr: "PET बाटल्या",
      ta: "PET பாட்டில்கள்",
      te: "PET సీసాలు",
      ml: "PET കുപ്പികൾ",
      gu: "PET બોટલો",
      pa: "PET ਬੋਤਲਾਂ",
      ur: "PET بوتلیں",
      ar: "زجاجات PET",
      as: "PET বটল",
      ne: "PET बोतल",
      es: "Botellas de PET",
      fr: "Bouteilles en PET",
      vi: "Chai PET",
      si: "PET බෝතල්",
      th: "ขวด PET",
      ru: "Бутылки PET",
      de: "PET-Flaschen",
      or: "PET ବୋତଲ",
      ja: "PETボトル",
      uk: "Пляшки PET",
      ko: "PET병",
      it: "Bottiglie PET",
      pl: "Butelki PET",
      tr: "PET şişeler",
      zh: "PET瓶",
      pt: "Garrafas PET",
      id: "Botol PET",
      nl: "PET-flessen",
      ms: "Botol PET",
    },
    floorPaise: 1600,
    fallbackPaise: 2000,
    co2eFactor: 1.5,
  },
  {
    code: "PLASTIC-HDPE",
    family: "plastic",
    stage: "scrap",
    names: {
      en: "Hard plastic (HDPE)",
      hi: "सख़्त प्लास्टिक",
      kn: "ಗಟ್ಟಿ ಪ್ಲಾಸ್ಟಿಕ್",
      bn: "শক্ত প্লাস্টিক (HDPE)",
      mr: "कठीण प्लास्टिक (HDPE)",
      ta: "கடின பிளாஸ்டிக் (HDPE)",
      te: "గట్టి ప్లాస్టిక్ (HDPE)",
      ml: "കട്ടിയുള്ള പ്ലാസ്റ്റിക് (HDPE)",
      gu: "સખત પ્લાસ્ટિક (HDPE)",
      pa: "ਸਖ਼ਤ ਪਲਾਸਟਿਕ (HDPE)",
      ur: "سخت پلاسٹک (HDPE)",
      ar: "بلاستيك صلب (HDPE)",
      as: "কঠিন প্লাষ্টিক (HDPE)",
      ne: "कडा प्लास्टिक (HDPE)",
      es: "Plástico rígido (HDPE)",
      fr: "Plastique rigide (PEHD)",
      vi: "Nhựa cứng (HDPE)",
      si: "දෘඩ ප්ලාස්ටික් (HDPE)",
      th: "พลาสติกแข็ง (HDPE)",
      ru: "Жёсткий пластик (HDPE)",
      de: "Hartkunststoff (HDPE)",
      or: "କଠିନ ପ୍ଲାଷ୍ଟିକ୍ (HDPE)",
      ja: "硬質プラスチック（HDPE）",
      uk: "Твердий пластик (HDPE)",
      ko: "단단한 플라스틱(HDPE)",
      it: "Plastica rigida (HDPE)",
      pl: "Twardy plastik (HDPE)",
      tr: "Sert plastik (HDPE)",
      zh: "硬塑料（HDPE）",
      pt: "Plástico rígido (HDPE)",
      id: "Plastik keras (HDPE)",
      nl: "Hard plastic (HDPE)",
      ms: "Plastik keras (HDPE)",
    },
    floorPaise: 1800,
    fallbackPaise: 2200,
    co2eFactor: 1,
  },
  {
    code: "PLASTIC-PP",
    family: "plastic",
    stage: "scrap",
    names: {
      en: "Plastic containers (PP)",
      hi: "प्लास्टिक डिब्बे",
      kn: "ಪ್ಲಾಸ್ಟಿಕ್ ಡಬ್ಬಿ",
      bn: "প্লাস্টিকের পাত্র (PP)",
      mr: "प्लास्टिकचे डबे (PP)",
      ta: "பிளாஸ்டிக் கொள்கலன்கள் (PP)",
      te: "ప్లాస్టిక్ డబ్బాలు (PP)",
      ml: "പ്ലാസ്റ്റിക് പാത്രങ്ങൾ (PP)",
      gu: "પ્લાસ્ટિકના ડબ્બા (PP)",
      pa: "ਪਲਾਸਟਿਕ ਦੇ ਡੱਬੇ (PP)",
      ur: "پلاسٹک کے ڈبے (PP)",
      ar: "عبوات بلاستيكية (PP)",
      as: "প্লাষ্টিকৰ পাত্ৰ (PP)",
      ne: "प्लास्टिकका भाँडा (PP)",
      es: "Recipientes de plástico (PP)",
      fr: "Contenants en plastique (PP)",
      vi: "Hộp nhựa (PP)",
      si: "ප්ලාස්ටික් බඳුන් (PP)",
      th: "ภาชนะพลาสติก (PP)",
      ru: "Пластиковые ёмкости (PP)",
      de: "Kunststoffbehälter (PP)",
      or: "ପ୍ଲାଷ୍ଟିକ୍ ପାତ୍ର (PP)",
      ja: "プラスチック容器（PP）",
      uk: "Пластикові місткості (PP)",
      ko: "플라스틱 용기(PP)",
      it: "Contenitori di plastica (PP)",
      pl: "Pojemniki plastikowe (PP)",
      tr: "Plastik kaplar (PP)",
      zh: "塑料容器（PP）",
      pt: "Recipientes plásticos (PP)",
      id: "Wadah plastik (PP)",
      nl: "Plastic bakken (PP)",
      ms: "Bekas plastik (PP)",
    },
    floorPaise: 1400,
    fallbackPaise: 1800,
    co2eFactor: 1,
  },
  {
    code: "PLASTIC-LDPE",
    family: "plastic",
    stage: "scrap",
    names: {
      en: "Plastic covers (LDPE)",
      hi: "प्लास्टिक थैलियाँ",
      kn: "ಪ್ಲಾಸ್ಟಿಕ್ ಕವರ್",
      bn: "প্লাস্টিকের ব্যাগ (LDPE)",
      mr: "प्लास्टिकच्या पिशव्या (LDPE)",
      ta: "பிளாஸ்டிக் பைகள் (LDPE)",
      te: "ప్లాస్టిక్ సంచులు (LDPE)",
      ml: "പ്ലാസ്റ്റിക് കവറുകൾ (LDPE)",
      gu: "પ્લાસ્ટિકની થેલીઓ (LDPE)",
      pa: "ਪਲਾਸਟਿਕ ਦੇ ਲਿਫ਼ਾਫ਼ੇ (LDPE)",
      ur: "پلاسٹک کی تھیلیاں (LDPE)",
      ar: "أكياس بلاستيكية (LDPE)",
      as: "প্লাষ্টিকৰ আৱৰণ (LDPE)",
      ne: "प्लास्टिकका आवरण (LDPE)",
      es: "Bolsas y envoltorios de plástico (LDPE)",
      fr: "Films et sacs plastiques (PEBD)",
      vi: "Túi và màng nhựa (LDPE)",
      si: "ප්ලාස්ටික් ආවරණ (LDPE)",
      th: "ถุงพลาสติก (LDPE)",
      ru: "Пластиковые пакеты и плёнка (LDPE)",
      de: "Kunststofffolien (LDPE)",
      or: "ପ୍ଲାଷ୍ଟିକ୍ ଆବରଣ (LDPE)",
      ja: "プラスチック袋（LDPE）",
      uk: "Пластикові пакети й плівка (LDPE)",
      ko: "비닐봉지(LDPE)",
      it: "Pellicole di plastica (LDPE)",
      pl: "Folie plastikowe (LDPE)",
      tr: "Plastik poşetler (LDPE)",
      zh: "塑料袋（LDPE）",
      pt: "Filmes plásticos (LDPE)",
      id: "Kantong plastik (LDPE)",
      nl: "Plastic folie (LDPE)",
      ms: "Beg plastik (LDPE)",
    },
    floorPaise: 800,
    fallbackPaise: 1000,
    co2eFactor: 1,
  },
  {
    code: "PLASTIC-MIXED",
    family: "plastic",
    stage: "scrap",
    names: {
      en: "Mixed plastic",
      hi: "मिक्स प्लास्टिक",
      kn: "ಮಿಶ್ರ ಪ್ಲಾಸ್ಟಿಕ್",
      bn: "মিশ্র প্লাস্টিক",
      mr: "मिश्र प्लास्टिक",
      ta: "கலப்பு பிளாஸ்டிக்",
      te: "మిశ్రమ ప్లాస్టిక్",
      ml: "മിശ്രിത പ്ലാസ്റ്റിക്",
      gu: "મિશ્ર પ્લાસ્ટિક",
      pa: "ਮਿਲਿਆ-ਜੁਲਿਆ ਪਲਾਸਟਿਕ",
      ur: "ملا جلا پلاسٹک",
      ar: "بلاستيك مختلط",
      as: "মিশ্ৰ প্লাষ্টিক",
      ne: "मिसिएको प्लास्टिक",
      es: "Plástico mezclado",
      fr: "Plastiques mélangés",
      vi: "Nhựa hỗn hợp",
      si: "මිශ්‍ර ප්ලාස්ටික්",
      th: "พลาสติกคละชนิด",
      ru: "Смешанный пластик",
      de: "Gemischte Kunststoffe",
      or: "ମିଶ୍ରିତ ପ୍ଲାଷ୍ଟିକ୍",
      ja: "混合プラスチック",
      uk: "Змішаний пластик",
      ko: "혼합 플라스틱",
      it: "Plastica mista",
      pl: "Plastik mieszany",
      tr: "Karışık plastik",
      zh: "混合塑料",
      pt: "Plástico misto",
      id: "Plastik campuran",
      nl: "Gemengd plastic",
      ms: "Plastik bercampur",
    },
    floorPaise: 400,
    fallbackPaise: 600,
    co2eFactor: 0.8,
  },
  {
    code: "METAL-IRON",
    family: "metal",
    stage: "scrap",
    names: {
      en: "Iron and steel",
      hi: "लोहा",
      kn: "ಕಬ್ಬಿಣ",
      bn: "লোহা ও ইস্পাত",
      mr: "लोखंड आणि पोलाद",
      ta: "இரும்பு மற்றும் எஃகு",
      te: "ఇనుము మరియు ఉక్కు",
      ml: "ഇരുമ്പും ഉരുക്കും",
      gu: "લોખંડ અને પોલાદ",
      pa: "ਲੋਹਾ ਅਤੇ ਇਸਪਾਤ",
      ur: "لوہا اور فولاد",
      ar: "حديد وفولاذ",
      as: "লোহা আৰু তীখা",
      ne: "फलाम र इस्पात",
      es: "Hierro y acero",
      fr: "Fer et acier",
      vi: "Sắt và thép",
      si: "යකඩ සහ වානේ",
      th: "เหล็กและเหล็กกล้า",
      ru: "Железо и сталь",
      de: "Eisen und Stahl",
      or: "ଲୁହା ଓ ଇସ୍ପାତ",
      ja: "鉄・鋼",
      uk: "Залізо й сталь",
      ko: "철과 강철",
      it: "Ferro e acciaio",
      pl: "Żelazo i stal",
      tr: "Demir ve çelik",
      zh: "铁和钢",
      pt: "Ferro e aço",
      id: "Besi dan baja",
      nl: "IJzer en staal",
      ms: "Besi dan keluli",
    },
    floorPaise: 2400,
    fallbackPaise: 2800,
    co2eFactor: 1.5,
  },
  {
    code: "METAL-SS",
    family: "metal",
    stage: "scrap",
    names: {
      en: "Stainless steel",
      hi: "स्टेनलेस स्टील",
      kn: "ಸ್ಟೀಲ್",
      bn: "মরিচারোধী ইস্পাত",
      mr: "स्टेनलेस स्टील",
      ta: "துருப்பிடிக்காத எஃகு",
      te: "తుప్పు పట్టని ఉక్కు",
      ml: "തുരുമ്പിക്കാത്ത ഉരുക്ക്",
      gu: "કાટરહિત પોલાદ",
      pa: "ਜੰਗਾਲ-ਰਹਿਤ ਇਸਪਾਤ",
      ur: "زنگ سے محفوظ فولاد",
      ar: "فولاذ مقاوم للصدأ",
      as: "মৰিচা নধৰা তীখা",
      ne: "खिया नलाग्ने इस्पात",
      es: "Acero inoxidable",
      fr: "Acier inoxydable",
      vi: "Thép không gỉ",
      si: "මල නොබැඳෙන වානේ",
      th: "สเตนเลส",
      ru: "Нержавеющая сталь",
      de: "Edelstahl",
      or: "କଳଙ୍କି ନଲାଗୁଥିବା ଇସ୍ପାତ",
      ja: "ステンレス鋼",
      uk: "Нержавіюча сталь",
      ko: "스테인리스강",
      it: "Acciaio inossidabile",
      pl: "Stal nierdzewna",
      tr: "Paslanmaz çelik",
      zh: "不锈钢",
      pt: "Aço inoxidável",
      id: "Baja tahan karat",
      nl: "Roestvrij staal",
      ms: "Keluli tahan karat",
    },
    floorPaise: 4500,
    fallbackPaise: 5500,
    co2eFactor: 1.5,
  },
  {
    code: "METAL-ALU-CAN",
    family: "metal",
    stage: "scrap",
    names: {
      en: "Aluminium cans",
      hi: "एल्युमिनियम कैन",
      kn: "ಅಲ್ಯೂಮಿನಿಯಂ ಕ್ಯಾನ್",
      bn: "অ্যালুমিনিয়ামের ক্যান",
      mr: "ॲल्युमिनियमचे कॅन",
      ta: "அலுமினிய கேன்கள்",
      te: "అల్యూమినియం క్యాన్లు",
      ml: "അലുമിനിയം കാനുകൾ",
      gu: "એલ્યુમિનિયમના કેન",
      pa: "ਐਲੂਮੀਨੀਅਮ ਦੇ ਕੈਨ",
      ur: "ایلومینیم کے کین",
      ar: "علب ألمنيوم",
      as: "এলুমিনিয়ামৰ কেন",
      ne: "अलुमिनियमका क्यान",
      es: "Latas de aluminio",
      fr: "Canettes en aluminium",
      vi: "Lon nhôm",
      si: "ඇලුමිනියම් කෑන්",
      th: "กระป๋องอะลูมิเนียม",
      ru: "Алюминиевые банки",
      de: "Aluminiumdosen",
      or: "ଆଲୁମିନିୟମ୍ କ୍ୟାନ୍",
      ja: "アルミ缶",
      uk: "Алюмінієві банки",
      ko: "알루미늄 캔",
      it: "Lattine di alluminio",
      pl: "Puszki aluminiowe",
      tr: "Alüminyum kutular",
      zh: "铝罐",
      pt: "Latas de alumínio",
      id: "Kaleng aluminium",
      nl: "Aluminium blikjes",
      ms: "Tin aluminium",
    },
    floorPaise: 9000,
    fallbackPaise: 11_000,
    co2eFactor: 9,
  },
  {
    code: "METAL-ALU",
    family: "metal",
    stage: "scrap",
    names: {
      en: "Aluminium (utensils)",
      hi: "एल्युमिनियम बर्तन",
      kn: "ಅಲ್ಯೂಮಿನಿಯಂ ಪಾತ್ರೆ",
      bn: "অ্যালুমিনিয়ামের বাসন",
      mr: "ॲल्युमिनियमची भांडी",
      ta: "அலுமினிய பாத்திரங்கள்",
      te: "అల్యూమినియం పాత్రలు",
      ml: "അലുമിനിയം പാത്രങ്ങൾ",
      gu: "એલ્યુમિનિયમનાં વાસણો",
      pa: "ਐਲੂਮੀਨੀਅਮ ਦੇ ਭਾਂਡੇ",
      ur: "ایلومینیم کے برتن",
      ar: "أواني ألمنيوم",
      as: "এলুমিনিয়ামৰ বাচন",
      ne: "अलुमिनियम (भाँडा)",
      es: "Aluminio (utensilios)",
      fr: "Aluminium (ustensiles)",
      vi: "Nhôm (đồ dùng)",
      si: "ඇලුමිනියම් (භාජන)",
      th: "อะลูมิเนียม (เครื่องใช้)",
      ru: "Алюминий (посуда)",
      de: "Aluminiumgegenstände",
      or: "ଆଲୁମିନିୟମ୍ ବାସନ",
      ja: "アルミニウム（器具類）",
      uk: "Алюміній (посуд)",
      ko: "알루미늄(생활용품)",
      it: "Alluminio (utensili)",
      pl: "Przedmioty aluminiowe",
      tr: "Alüminyum (mutfak eşyaları)",
      zh: "铝制器具",
      pt: "Alumínio (utensílios)",
      id: "Aluminium (peralatan dapur)",
      nl: "Aluminium (keukengerei)",
      ms: "Aluminium (perkakas dapur)",
    },
    floorPaise: 11_000,
    fallbackPaise: 13_000,
    co2eFactor: 9,
  },
  {
    code: "METAL-COPPER",
    family: "metal",
    stage: "scrap",
    names: {
      en: "Copper",
      hi: "तांबा",
      kn: "ತಾಮ್ರ",
      bn: "তামা",
      mr: "तांबे",
      ta: "செம்பு",
      te: "రాగి",
      ml: "ചെമ്പ്",
      gu: "તાંબું",
      pa: "ਤਾਂਬਾ",
      ur: "تانبا",
      ar: "نحاس",
      as: "তাম",
      ne: "तामा",
      es: "Cobre",
      fr: "Cuivre",
      vi: "Đồng",
      si: "තඹ",
      th: "ทองแดง",
      ru: "Медь",
      de: "Kupfer",
      or: "ତମ୍ବା",
      ja: "銅",
      uk: "Мідь",
      ko: "구리",
      it: "Rame",
      pl: "Miedź",
      tr: "Bakır",
      zh: "铜",
      pt: "Cobre",
      id: "Tembaga",
      nl: "Koper",
      ms: "Tembaga",
    },
    floorPaise: 55_000,
    fallbackPaise: 65_000,
    co2eFactor: 3,
  },
  {
    code: "METAL-BRASS",
    family: "metal",
    stage: "scrap",
    names: {
      en: "Brass",
      hi: "पीतल",
      kn: "ಹಿತ್ತಾಳೆ",
      bn: "পিতল",
      mr: "पितळ",
      ta: "பித்தளை",
      te: "ఇత్తడి",
      ml: "പിച്ചള",
      gu: "પિત્તળ",
      pa: "ਪਿੱਤਲ",
      ur: "پیتل",
      ar: "نحاس أصفر",
      as: "পিতল",
      ne: "पित्तल",
      es: "Latón",
      fr: "Laiton",
      vi: "Đồng thau",
      si: "පිත්තල",
      th: "ทองเหลือง",
      ru: "Латунь",
      de: "Messing",
      or: "ପିତ୍ତଳ",
      ja: "真ちゅう",
      uk: "Латунь",
      ko: "황동",
      it: "Ottone",
      pl: "Mosiądz",
      tr: "Pirinç",
      zh: "黄铜",
      pt: "Latão",
      id: "Kuningan",
      nl: "Messing",
      ms: "Loyang",
    },
    floorPaise: 32_000,
    fallbackPaise: 38_000,
    co2eFactor: 2.5,
  },
  {
    code: "GLASS-BOTTLE",
    family: "glass",
    stage: "scrap",
    names: {
      en: "Glass bottles",
      hi: "काँच की बोतलें",
      kn: "ಗಾಜಿನ ಬಾಟಲಿ",
      bn: "কাচের বোতল",
      mr: "काचेच्या बाटल्या",
      ta: "கண்ணாடி பாட்டில்கள்",
      te: "గాజు సీసాలు",
      ml: "ചില്ലുകുപ്പികൾ",
      gu: "કાચની બોટલો",
      pa: "ਕੱਚ ਦੀਆਂ ਬੋਤਲਾਂ",
      ur: "شیشے کی بوتلیں",
      ar: "زجاجات زجاجية",
      as: "কাঁচৰ বটল",
      ne: "सिसाका बोतल",
      es: "Botellas de vidrio",
      fr: "Bouteilles en verre",
      vi: "Chai thủy tinh",
      si: "වීදුරු බෝතල්",
      th: "ขวดแก้ว",
      ru: "Стеклянные бутылки",
      de: "Glasflaschen",
      or: "କାଚ ବୋତଲ",
      ja: "ガラス瓶",
      uk: "Скляні пляшки",
      ko: "유리병",
      it: "Bottiglie di vetro",
      pl: "Butelki szklane",
      tr: "Cam şişeler",
      zh: "玻璃瓶",
      pt: "Garrafas de vidro",
      id: "Botol kaca",
      nl: "Glazen flessen",
      ms: "Botol kaca",
    },
    floorPaise: 100,
    fallbackPaise: 200,
    co2eFactor: 0.3,
  },
  {
    code: "EWASTE-SMALL",
    family: "ewaste",
    stage: "scrap",
    names: {
      en: "Small electronics",
      hi: "छोटे इलेक्ट्रॉनिक्स",
      kn: "ಸಣ್ಣ ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್",
      bn: "ছোট ইলেকট্রনিক যন্ত্র",
      mr: "लहान इलेक्ट्रॉनिक उपकरणे",
      ta: "சிறிய மின்னணுச் சாதனங்கள்",
      te: "చిన్న ఎలక్ట్రానిక్ పరికరాలు",
      ml: "ചെറിയ ഇലക്ട്രോണിക് ഉപകരണങ്ങൾ",
      gu: "નાનાં ઇલેક્ટ્રોનિક ઉપકરણો",
      pa: "ਛੋਟੇ ਇਲੈਕਟ੍ਰਾਨਿਕ ਉਪਕਰਨ",
      ur: "چھوٹے الیکٹرانک آلات",
      ar: "أجهزة إلكترونية صغيرة",
      as: "সৰু বৈদ্যুতিন যন্ত্ৰ",
      ne: "साना विद्युतीय सामान",
      es: "Aparatos electrónicos pequeños",
      fr: "Petits appareils électroniques",
      vi: "Thiết bị điện tử nhỏ",
      si: "කුඩා විදුලි උපකරණ",
      th: "อุปกรณ์อิเล็กทรอนิกส์ขนาดเล็ก",
      ru: "Мелкая электроника",
      de: "Kleine Elektrogeräte",
      or: "ଛୋଟ ଇଲେକ୍ଟ୍ରୋନିକ୍ ଯନ୍ତ୍ର",
      ja: "小型電子機器",
      uk: "Дрібна електроніка",
      ko: "소형 전자제품",
      it: "Piccoli dispositivi elettronici",
      pl: "Małe urządzenia elektroniczne",
      tr: "Küçük elektronik eşyalar",
      zh: "小型电子设备",
      pt: "Pequenos eletrônicos",
      id: "Elektronik kecil",
      nl: "Kleine elektronica",
      ms: "Peralatan elektronik kecil",
    },
    floorPaise: 2000,
    fallbackPaise: 3000,
    co2eFactor: 2,
  },
  {
    code: "EWASTE-PHONE",
    family: "ewaste",
    stage: "scrap",
    names: {
      en: "Old mobile phones",
      hi: "पुराने मोबाइल",
      kn: "ಹಳೆಯ ಮೊಬೈಲ್",
      bn: "পুরোনো মোবাইল ফোন",
      mr: "जुने मोबाइल फोन",
      ta: "பழைய கைப்பேசிகள்",
      te: "పాత మొబైల్ ఫోన్లు",
      ml: "പഴയ മൊബൈൽ ഫോണുകൾ",
      gu: "જૂના મોબાઇલ ફોન",
      pa: "ਪੁਰਾਣੇ ਮੋਬਾਈਲ ਫ਼ੋਨ",
      ur: "پرانے موبائل فون",
      ar: "هواتف محمولة قديمة",
      as: "পুৰণি ম'বাইল ফোন",
      ne: "पुराना मोबाइल फोन",
      es: "Móviles usados",
      fr: "Anciens téléphones portables",
      vi: "Điện thoại di động cũ",
      si: "පරණ ජංගම දුරකථන",
      th: "โทรศัพท์มือถือเก่า",
      ru: "Старые мобильные телефоны",
      de: "Alte Mobiltelefone",
      or: "ପୁରୁଣା ମୋବାଇଲ୍ ଫୋନ୍",
      ja: "古い携帯電話",
      uk: "Старі мобільні телефони",
      ko: "헌 휴대전화",
      it: "Cellulari usati",
      pl: "Stare telefony",
      tr: "Eski cep telefonları",
      zh: "旧手机",
      pt: "Celulares usados",
      id: "Ponsel lama",
      nl: "Oude mobiele telefoons",
      ms: "Telefon bimbit lama",
    },
    floorPaise: 10_000,
    fallbackPaise: 15_000,
    co2eFactor: 2,
  },
  {
    code: "EWASTE-CABLE",
    family: "ewaste",
    stage: "scrap",
    names: {
      en: "Wires and cables",
      hi: "तार और केबल",
      kn: "ತಂತಿ ಮತ್ತು ಕೇಬಲ್",
      bn: "তার ও কেবল",
      mr: "तारा आणि केबल",
      ta: "கம்பிகள் மற்றும் கேபிள்கள்",
      te: "తీగలు మరియు కేబుళ్లు",
      ml: "വയറുകളും കേബിളുകളും",
      gu: "તાર અને કેબલ",
      pa: "ਤਾਰਾਂ ਅਤੇ ਕੇਬਲਾਂ",
      ur: "تار اور کیبل",
      ar: "أسلاك وكابلات",
      as: "তাঁৰ আৰু কেবল",
      ne: "तार र केबल",
      es: "Hilos y cables",
      fr: "Fils et câbles",
      vi: "Dây điện và cáp",
      si: "කම්බි සහ කේබල්",
      th: "สายไฟและสายเคเบิล",
      ru: "Провода и кабели",
      de: "Drähte und Kabel",
      or: "ତାର ଓ କେବୁଲ୍",
      ja: "電線・ケーブル",
      uk: "Дроти й кабелі",
      ko: "전선과 케이블",
      it: "Fili e cavi",
      pl: "Przewody i kable",
      tr: "Teller ve kablolar",
      zh: "电线和电缆",
      pt: "Fios e cabos",
      id: "Kawat dan kabel",
      nl: "Draden en kabels",
      ms: "Wayar dan kabel",
    },
    floorPaise: 8000,
    fallbackPaise: 10_000,
    co2eFactor: 2,
  },
  {
    code: "EWASTE-BATTERY",
    family: "ewaste",
    stage: "scrap",
    names: {
      en: "Lead batteries",
      hi: "बैटरी (इन्वर्टर, गाड़ी)",
      kn: "ಬ್ಯಾಟರಿ (ಇನ್ವರ್ಟರ್, ವಾಹನ)",
      bn: "সিসার ব্যাটারি",
      mr: "शिशाच्या बॅटऱ्या",
      ta: "ஈய மின்கலங்கள்",
      te: "సీసం బ్యాటరీలు",
      ml: "ലെഡ് ബാറ്ററികൾ",
      gu: "સીસાની બેટરીઓ",
      pa: "ਸਿੱਕੇ ਦੀਆਂ ਬੈਟਰੀਆਂ",
      ur: "سیسے کی بیٹریاں",
      ar: "بطاريات رصاص",
      as: "সীহৰ বেটাৰী",
      ne: "सिसायुक्त ब्याट्री",
      es: "Baterías de plomo",
      fr: "Batteries au plomb",
      vi: "Ắc quy chì",
      si: "ඊයම් බැටරි",
      th: "แบตเตอรี่ตะกั่ว",
      ru: "Свинцовые аккумуляторы",
      de: "Bleibatterien",
      or: "ସୀସା ବ୍ୟାଟେରି",
      ja: "鉛蓄電池",
      uk: "Свинцеві акумулятори",
      ko: "납축전지",
      it: "Batterie al piombo",
      pl: "Akumulatory ołowiowe",
      tr: "Kurşun aküler",
      zh: "铅蓄电池",
      pt: "Baterias de chumbo",
      id: "Aki timbal",
      nl: "Loodaccu's",
      ms: "Bateri plumbum",
    },
    floorPaise: 7000,
    fallbackPaise: 8500,
    co2eFactor: 1,
  },
  {
    code: "OTHER-CLOTHES",
    family: "other",
    stage: "scrap",
    names: {
      en: "Old clothes",
      hi: "पुराने कपड़े",
      kn: "ಹಳೆಯ ಬಟ್ಟೆ",
      bn: "পুরোনো জামাকাপড়",
      mr: "जुने कपडे",
      ta: "பழைய துணிகள்",
      te: "పాత బట్టలు",
      ml: "പഴയ വസ്ത്രങ്ങൾ",
      gu: "જૂનાં કપડાં",
      pa: "ਪੁਰਾਣੇ ਕੱਪੜੇ",
      ur: "پرانے کپڑے",
      ar: "ملابس قديمة",
      as: "পুৰণি কাপোৰ",
      ne: "पुराना कपडा",
      es: "Ropa usada",
      fr: "Vêtements usagés",
      vi: "Quần áo cũ",
      si: "පරණ ඇඳුම්",
      th: "เสื้อผ้าเก่า",
      ru: "Старая одежда",
      de: "Altkleider",
      or: "ପୁରୁଣା ପୋଷାକ",
      ja: "古着",
      uk: "Старий одяг",
      ko: "헌 옷",
      it: "Vestiti usati",
      pl: "Stare ubrania",
      tr: "Eski giysiler",
      zh: "旧衣物",
      pt: "Roupas usadas",
      id: "Pakaian lama",
      nl: "Oude kleding",
      ms: "Pakaian lama",
    },
    floorPaise: 300,
    fallbackPaise: 500,
    co2eFactor: 3,
  },
  // Recycled output: what recyclers sell to manufacturers. Prices are per kg
  // at the factory gate; floor and fallback don't apply to households here.
  {
    code: "RECYCLED-PET-FLAKE",
    family: "plastic",
    stage: "recycled",
    names: {
      en: "Recycled PET flakes",
      hi: "रीसायकल्ड पेट फ़्लेक्स",
      kn: "ಮರುಬಳಕೆ ಪೆಟ್ ಫ್ಲೇಕ್ಸ್",
      bn: "পুনর্ব্যবহৃত PET কুচি",
      mr: "पुनर्प्रक्रिया केलेले PET तुकडे",
      ta: "மறுசுழற்சி செய்யப்பட்ட PET துகள்கள்",
      te: "రీసైకిల్ చేసిన PET తునకలు",
      ml: "പുനഃസംസ്കരിച്ച PET ചീളുകൾ",
      gu: "રિસાયકલ કરેલા PET ટુકડા",
      pa: "ਰੀਸਾਈਕਲ ਕੀਤੇ PET ਟੁਕੜੇ",
      ur: "ری سائیکل شدہ PET کے ٹکڑے",
      ar: "رقائق PET معاد تدويرها",
      as: "পুনঃপ্ৰক্ৰিয়াকৃত PET টুকুৰা",
      ne: "पुनर्चक्रित PET चिप्स",
      es: "Escamas de PET reciclado",
      fr: "Paillettes de PET recyclé",
      vi: "Mảnh PET tái chế",
      si: "ප්‍රතිචක්‍රීකරණ PET පතුරු",
      th: "เกล็ด PET รีไซเคิล",
      ru: "Вторичные хлопья PET",
      de: "Recycelte PET-Flakes",
      or: "ପୁନଃପ୍ରକ୍ରିୟାକୃତ PET ଖଣ୍ଡ",
      ja: "再生PETフレーク",
      uk: "Вторинні пластівці PET",
      ko: "재활용 PET 플레이크",
      it: "Scaglie di PET riciclato",
      pl: "Płatki PET z recyklingu",
      tr: "Geri dönüştürülmüş PET pulları",
      zh: "再生PET碎片",
      pt: "Flocos de PET reciclado",
      id: "Serpihan PET daur ulang",
      nl: "Gerecyclede PET-vlokken",
      ms: "Serpihan PET kitar semula",
    },
    floorPaise: 5500,
    fallbackPaise: 6500,
    co2eFactor: 1.5,
  },
  {
    code: "RECYCLED-HDPE-GRANULE",
    family: "plastic",
    stage: "recycled",
    names: {
      en: "Recycled HDPE granules",
      hi: "रीसायकल्ड HDPE दाने",
      kn: "ಮರುಬಳಕೆ HDPE ಕಣಗಳು",
      bn: "পুনর্ব্যবহৃত HDPE দানা",
      mr: "पुनर्प्रक्रिया केलेले HDPE दाणे",
      ta: "மறுசுழற்சி செய்யப்பட்ட HDPE மணிகள்",
      te: "రీసైకిల్ చేసిన HDPE గుళికలు",
      ml: "പുനഃസംസ്കരിച്ച HDPE തരികൾ",
      gu: "રિસાયકલ કરેલા HDPE દાણા",
      pa: "ਰੀਸਾਈਕਲ ਕੀਤੇ HDPE ਦਾਣੇ",
      ur: "ری سائیکل شدہ HDPE کے دانے",
      ar: "حبيبات HDPE معاد تدويرها",
      as: "পুনঃপ্ৰক্ৰিয়াকৃত HDPE দানা",
      ne: "पुनर्चक्रित HDPE दाना",
      es: "Granza de HDPE reciclado",
      fr: "Granulés de PEHD recyclé",
      vi: "Hạt HDPE tái chế",
      si: "ප්‍රතිචක්‍රීකරණ HDPE කැටිති",
      th: "เม็ด HDPE รีไซเคิล",
      ru: "Вторичные гранулы HDPE",
      de: "Recyceltes HDPE-Granulat",
      or: "ପୁନଃପ୍ରକ୍ରିୟାକୃତ HDPE ଦାନା",
      ja: "再生HDPE粒",
      uk: "Вторинні гранули HDPE",
      ko: "재활용 HDPE 과립",
      it: "Granuli di HDPE riciclato",
      pl: "Granulat HDPE z recyklingu",
      tr: "Geri dönüştürülmüş HDPE granülleri",
      zh: "再生HDPE颗粒",
      pt: "Grânulos de HDPE reciclado",
      id: "Butiran HDPE daur ulang",
      nl: "Gerecyclede HDPE-korrels",
      ms: "Butiran HDPE kitar semula",
    },
    floorPaise: 6000,
    fallbackPaise: 7000,
    co2eFactor: 1,
  },
  {
    code: "RECYCLED-KRAFT",
    family: "paper",
    stage: "recycled",
    names: {
      en: "Recycled kraft paper",
      hi: "रीसायकल्ड क्राफ़्ट पेपर",
      kn: "ಮರುಬಳಕೆ ಕ್ರಾಫ್ಟ್ ಕಾಗದ",
      bn: "পুনর্ব্যবহৃত ক্রাফট কাগজ",
      mr: "पुनर्प्रक्रिया केलेला क्राफ्ट कागद",
      ta: "மறுசுழற்சி செய்யப்பட்ட கிராஃப்ட் காகிதம்",
      te: "రీసైకిల్ చేసిన క్రాఫ్ట్ కాగితం",
      ml: "പുനഃസംസ്കരിച്ച ക്രാഫ്റ്റ് കടലാസ്",
      gu: "રિસાયકલ કરેલો ક્રાફ્ટ કાગળ",
      pa: "ਰੀਸਾਈਕਲ ਕੀਤਾ ਕਰਾਫ਼ਟ ਕਾਗਜ਼",
      ur: "ری سائیکل شدہ کرافٹ کاغذ",
      ar: "ورق كرافت معاد تدويره",
      as: "পুনঃপ্ৰক্ৰিয়াকৃত ক্ৰাফ্ট কাগজ",
      ne: "पुनर्चक्रित क्राफ्ट कागज",
      es: "Papel kraft reciclado",
      fr: "Papier kraft recyclé",
      vi: "Giấy kraft tái chế",
      si: "ප්‍රතිචක්‍රීකරණ ක්‍රාෆ්ට් කඩදාසි",
      th: "กระดาษคราฟต์รีไซเคิล",
      ru: "Вторичная крафт-бумага",
      de: "Recyceltes Kraftpapier",
      or: "ପୁନଃପ୍ରକ୍ରିୟାକୃତ କ୍ରାଫ୍ଟ କାଗଜ",
      ja: "再生クラフト紙",
      uk: "Вторинний крафт-папір",
      ko: "재활용 크라프트지",
      it: "Carta kraft riciclata",
      pl: "Papier kraft z recyklingu",
      tr: "Geri dönüştürülmüş kraft kâğıdı",
      zh: "再生牛皮纸",
      pt: "Papel kraft reciclado",
      id: "Kertas kraft daur ulang",
      nl: "Gerecycled kraftpapier",
      ms: "Kertas kraft kitar semula",
    },
    floorPaise: 3200,
    fallbackPaise: 3800,
    co2eFactor: 1,
  },
  {
    code: "RECYCLED-ALU-INGOT",
    family: "metal",
    stage: "recycled",
    names: {
      en: "Recycled aluminium ingots",
      hi: "रीसायकल्ड एल्युमिनियम सिल्लियाँ",
      kn: "ಮರುಬಳಕೆ ಅಲ್ಯೂಮಿನಿಯಂ ಗಟ್ಟಿ",
      bn: "পুনর্ব্যবহৃত অ্যালুমিনিয়ামের বাট",
      mr: "पुनर्प्रक्रिया केलेल्या ॲल्युमिनियमच्या लगडी",
      ta: "மறுசுழற்சி செய்யப்பட்ட அலுமினியக் கட்டிகள்",
      te: "రీసైకిల్ చేసిన అల్యూమినియం కడ్డీలు",
      ml: "പുനഃസംസ്കരിച്ച അലുമിനിയം കട്ടികൾ",
      gu: "રિસાયકલ કરેલી એલ્યુમિનિયમની પાટો",
      pa: "ਰੀਸਾਈਕਲ ਕੀਤੀਆਂ ਐਲੂਮੀਨੀਅਮ ਦੀਆਂ ਸਿੱਲੀਆਂ",
      ur: "ری سائیکل شدہ ایلومینیم کی سِلیں",
      ar: "سبائك ألمنيوم معاد تدويرها",
      as: "পুনঃপ্ৰক্ৰিয়াকৃত এলুমিনিয়ামৰ পিণ্ড",
      ne: "पुनर्चक्रित अलुमिनियमका सिल्ला",
      es: "Lingotes de aluminio reciclado",
      fr: "Lingots d’aluminium recyclé",
      vi: "Thỏi nhôm tái chế",
      si: "ප්‍රතිචක්‍රීකරණ ඇලුමිනියම් කුට්ටි",
      th: "แท่งอะลูมิเนียมรีไซเคิล",
      ru: "Слитки вторичного алюминия",
      de: "Recycelte Aluminiumbarren",
      or: "ପୁନଃପ୍ରକ୍ରିୟାକୃତ ଆଲୁମିନିୟମ୍ ପିଣ୍ଡ",
      ja: "再生アルミインゴット",
      uk: "Зливки вторинного алюмінію",
      ko: "재활용 알루미늄 주괴",
      it: "Lingotti di alluminio riciclato",
      pl: "Wlewki aluminiowe z recyklingu",
      tr: "Geri dönüştürülmüş alüminyum külçeleri",
      zh: "再生铝锭",
      pt: "Lingotes de alumínio reciclado",
      id: "Batangan aluminium daur ulang",
      nl: "Gerecyclede aluminium ingots",
      ms: "Jongkong aluminium kitar semula",
    },
    floorPaise: 18_000,
    fallbackPaise: 21_000,
    co2eFactor: 9,
  },
];

/** How much more each step up the chain typically pays (prototype data). */
export const CHAIN_MARKUP: Record<"kabadiwala" | "yard" | "recycler", number> =
  {
    kabadiwala: 1.25, // a yard pays a kabadiwala ~25% over the household price
    yard: 1.45, // a recycler pays a yard ~45% over it
    recycler: 1.7, // a manufacturer pays a recycler ~70% over it
  };

export function catalogueEntry(code: string): CatalogueEntry | undefined {
  return CATALOGUE.find((entry) => entry.code === code);
}

/** A material's name in a language, falling back to English. */
export function materialName(
  names: Record<string, string> | undefined,
  locale: string,
  code: string,
): string {
  return names?.[locale] ?? names?.en ?? code;
}
