import type { Locale } from "../../src/i18n/locales";

/**
 * Luma.Green's material codes — the catalogue every screen, price and trade
 * uses. Edit this file to add or rename a material, then re-run the seed
 * (`npx convex run demo:reset`). Names are per language; anything missing
 * falls back to English.
 *
 * Prices are Bengaluru SAMPLE figures for the prototype (paise per kg), not
 * market data. CO2e factors are indicative (kg CO2e avoided per kg recycled
 * instead of made new), rounded from published averages such as the US EPA
 * WARM model — replace them with sourced factors before any public claim.
 */

export type Family =
  "paper" | "plastic" | "metal" | "glass" | "ewaste" | "other";

export interface CatalogueEntry {
  code: string;
  family: Family;
  /** Scrap is bought from households; recycled output is sold to factories. */
  stage: "scrap" | "recycled";
  names: Record<Locale, string>;
  /** Bengaluru sample prices, paise per kg: the admin floor and fallback. */
  floorPaise: number;
  fallbackPaise: number;
  co2eFactor: number;
}

export const CATALOGUE: readonly CatalogueEntry[] = [
  {
    code: "PAPER-NEWS",
    family: "paper",
    stage: "scrap",
    names: {
      en: "Newspaper",
      hi: "अख़बार (रद्दी)",
      kn: "ದಿನಪತ್ರಿಕೆ (ರದ್ದಿ)",
      bn: "খবরের কাগজ",
      mr: "वर्तमानपत्र",
      ta: "செய்தித்தாள்",
      te: "వార్తాపత్రిక",
      ml: "പത്രം",
      gu: "અખબાર",
      pa: "ਅਖ਼ਬਾਰ",
      ur: "اخبار",
      ar: "صحف",
    },
    floorPaise: 1200,
    fallbackPaise: 1400,
    co2eFactor: 1,
  },
  {
    code: "PAPER-CARTON",
    family: "paper",
    stage: "scrap",
    names: {
      en: "Cardboard boxes",
      hi: "गत्ता",
      kn: "ರಟ್ಟು ಡಬ್ಬಗಳು",
      bn: "কার্ডবোর্ডের বাক্স",
      mr: "पुठ्ठ्याचे खोके",
      ta: "அட்டைப் பெட்டிகள்",
      te: "అట్టపెట్టెలు",
      ml: "കാർഡ്ബോർഡ് പെട്ടികൾ",
      gu: "પૂંઠાનાં બોક્સ",
      pa: "ਗੱਤੇ ਦੇ ਡੱਬੇ",
      ur: "گتے کے ڈبے",
      ar: "صناديق كرتونية",
    },
    floorPaise: 800,
    fallbackPaise: 1000,
    co2eFactor: 1,
  },
  {
    code: "PAPER-BOOKS",
    family: "paper",
    stage: "scrap",
    names: {
      en: "Books and notebooks",
      hi: "किताबें और कॉपियाँ",
      kn: "ಪುಸ್ತಕ ಮತ್ತು ನೋಟ್‌ಬುಕ್",
      bn: "বই ও খাতা",
      mr: "पुस्तके आणि वह्या",
      ta: "புத்தகங்கள் மற்றும் குறிப்பேடுகள்",
      te: "పుస్తకాలు మరియు నోటుపుస్తకాలు",
      ml: "പുസ്തകങ്ങളും നോട്ടുപുസ്തകങ്ങളും",
      gu: "પુસ્તકો અને નોટબુક",
      pa: "ਕਿਤਾਬਾਂ ਅਤੇ ਕਾਪੀਆਂ",
      ur: "کتابیں اور کاپیاں",
      ar: "كتب ودفاتر",
    },
    floorPaise: 1000,
    fallbackPaise: 1200,
    co2eFactor: 1,
  },
  {
    code: "PAPER-OFFICE",
    family: "paper",
    stage: "scrap",
    names: {
      en: "White office paper",
      hi: "सफ़ेद कागज़",
      kn: "ಬಿಳಿ ಕಾಗದ",
      bn: "অফিসের সাদা কাগজ",
      mr: "कार्यालयातील पांढरा कागद",
      ta: "அலுவலக வெள்ளைக் காகிதம்",
      te: "కార్యాలయ తెల్ల కాగితం",
      ml: "ഓഫീസിലെ വെളുത്ത കടലാസ്",
      gu: "ઓફિસનો સફેદ કાગળ",
      pa: "ਦਫ਼ਤਰ ਦਾ ਚਿੱਟਾ ਕਾਗਜ਼",
      ur: "دفتر کا سفید کاغذ",
      ar: "ورق مكتبي أبيض",
    },
    floorPaise: 1400,
    fallbackPaise: 1600,
    co2eFactor: 1,
  },
  {
    code: "PAPER-MIXED",
    family: "paper",
    stage: "scrap",
    names: {
      en: "Mixed paper",
      hi: "मिक्स कागज़",
      kn: "ಮಿಶ್ರ ಕಾಗದ",
      bn: "মিশ্র কাগজ",
      mr: "मिश्र कागद",
      ta: "கலப்புக் காகிதம்",
      te: "మిశ్రమ కాగితం",
      ml: "മിശ്രിത കടലാസ്",
      gu: "મિશ્ર કાગળ",
      pa: "ਮਿਲਿਆ-ਜੁਲਿਆ ਕਾਗਜ਼",
      ur: "ملا جلا کاغذ",
      ar: "ورق مختلط",
    },
    floorPaise: 600,
    fallbackPaise: 800,
    co2eFactor: 1,
  },
  {
    code: "PLASTIC-PET",
    family: "plastic",
    stage: "scrap",
    names: {
      en: "PET bottles",
      hi: "पेट बोतलें",
      kn: "ಪೆಟ್ ಬಾಟಲಿ",
      bn: "PET বোতল",
      mr: "PET बाटल्या",
      ta: "PET பாட்டில்கள்",
      te: "PET సీసాలు",
      ml: "PET കുപ്പികൾ",
      gu: "PET બોટલો",
      pa: "PET ਬੋਤਲਾਂ",
      ur: "PET بوتلیں",
      ar: "زجاجات PET",
    },
    floorPaise: 1600,
    fallbackPaise: 2000,
    co2eFactor: 1.5,
  },
  {
    code: "PLASTIC-HDPE",
    family: "plastic",
    stage: "scrap",
    names: {
      en: "Hard plastic (HDPE)",
      hi: "सख़्त प्लास्टिक",
      kn: "ಗಟ್ಟಿ ಪ್ಲಾಸ್ಟಿಕ್",
      bn: "শক্ত প্লাস্টিক (HDPE)",
      mr: "कठीण प्लास्टिक (HDPE)",
      ta: "கடின பிளாஸ்டிக் (HDPE)",
      te: "గట్టి ప్లాస్టిక్ (HDPE)",
      ml: "കട്ടിയുള്ള പ്ലാസ്റ്റിക് (HDPE)",
      gu: "સખત પ્લાસ્ટિક (HDPE)",
      pa: "ਸਖ਼ਤ ਪਲਾਸਟਿਕ (HDPE)",
      ur: "سخت پلاسٹک (HDPE)",
      ar: "بلاستيك صلب (HDPE)",
    },
    floorPaise: 1800,
    fallbackPaise: 2200,
    co2eFactor: 1,
  },
  {
    code: "PLASTIC-PP",
    family: "plastic",
    stage: "scrap",
    names: {
      en: "Plastic containers (PP)",
      hi: "प्लास्टिक डिब्बे",
      kn: "ಪ್ಲಾಸ್ಟಿಕ್ ಡಬ್ಬಿ",
      bn: "প্লাস্টিকের পাত্র (PP)",
      mr: "प्लास्टिकचे डबे (PP)",
      ta: "பிளாஸ்டிக் கொள்கலன்கள் (PP)",
      te: "ప్లాస్టిక్ డబ్బాలు (PP)",
      ml: "പ്ലാസ്റ്റിക് പാത്രങ്ങൾ (PP)",
      gu: "પ્લાસ્ટિકના ડબ્બા (PP)",
      pa: "ਪਲਾਸਟਿਕ ਦੇ ਡੱਬੇ (PP)",
      ur: "پلاسٹک کے ڈبے (PP)",
      ar: "عبوات بلاستيكية (PP)",
    },
    floorPaise: 1400,
    fallbackPaise: 1800,
    co2eFactor: 1,
  },
  {
    code: "PLASTIC-LDPE",
    family: "plastic",
    stage: "scrap",
    names: {
      en: "Plastic covers (LDPE)",
      hi: "प्लास्टिक थैलियाँ",
      kn: "ಪ್ಲಾಸ್ಟಿಕ್ ಕವರ್",
      bn: "প্লাস্টিকের ব্যাগ (LDPE)",
      mr: "प्लास्टिकच्या पिशव्या (LDPE)",
      ta: "பிளாஸ்டிக் பைகள் (LDPE)",
      te: "ప్లాస్టిక్ సంచులు (LDPE)",
      ml: "പ്ലാസ്റ്റിക് കവറുകൾ (LDPE)",
      gu: "પ્લાસ્ટિકની થેલીઓ (LDPE)",
      pa: "ਪਲਾਸਟਿਕ ਦੇ ਲਿਫ਼ਾਫ਼ੇ (LDPE)",
      ur: "پلاسٹک کی تھیلیاں (LDPE)",
      ar: "أكياس بلاستيكية (LDPE)",
    },
    floorPaise: 800,
    fallbackPaise: 1000,
    co2eFactor: 1,
  },
  {
    code: "PLASTIC-MIXED",
    family: "plastic",
    stage: "scrap",
    names: {
      en: "Mixed plastic",
      hi: "मिक्स प्लास्टिक",
      kn: "ಮಿಶ್ರ ಪ್ಲಾಸ್ಟಿಕ್",
      bn: "মিশ্র প্লাস্টিক",
      mr: "मिश्र प्लास्टिक",
      ta: "கலப்பு பிளாஸ்டிக்",
      te: "మిశ్రమ ప్లాస్టిక్",
      ml: "മിശ്രിത പ്ലാസ്റ്റിക്",
      gu: "મિશ્ર પ્લાસ્ટિક",
      pa: "ਮਿਲਿਆ-ਜੁਲਿਆ ਪਲਾਸਟਿਕ",
      ur: "ملا جلا پلاسٹک",
      ar: "بلاستيك مختلط",
    },
    floorPaise: 400,
    fallbackPaise: 600,
    co2eFactor: 0.8,
  },
  {
    code: "METAL-IRON",
    family: "metal",
    stage: "scrap",
    names: {
      en: "Iron and steel",
      hi: "लोहा",
      kn: "ಕಬ್ಬಿಣ",
      bn: "লোহা ও ইস্পাত",
      mr: "लोखंड आणि पोलाद",
      ta: "இரும்பு மற்றும் எஃகு",
      te: "ఇనుము మరియు ఉక్కు",
      ml: "ഇരുമ്പും ഉരുക്കും",
      gu: "લોખંડ અને પોલાદ",
      pa: "ਲੋਹਾ ਅਤੇ ਇਸਪਾਤ",
      ur: "لوہا اور فولاد",
      ar: "حديد وفولاذ",
    },
    floorPaise: 2400,
    fallbackPaise: 2800,
    co2eFactor: 1.5,
  },
  {
    code: "METAL-SS",
    family: "metal",
    stage: "scrap",
    names: {
      en: "Stainless steel",
      hi: "स्टेनलेस स्टील",
      kn: "ಸ್ಟೀಲ್",
      bn: "মরিচারোধী ইস্পাত",
      mr: "स्टेनलेस स्टील",
      ta: "துருப்பிடிக்காத எஃகு",
      te: "తుప్పు పట్టని ఉక్కు",
      ml: "തുരുമ്പിക്കാത്ത ഉരുക്ക്",
      gu: "કાટરહિત પોલાદ",
      pa: "ਜੰਗਾਲ-ਰਹਿਤ ਇਸਪਾਤ",
      ur: "زنگ سے محفوظ فولاد",
      ar: "فولاذ مقاوم للصدأ",
    },
    floorPaise: 4500,
    fallbackPaise: 5500,
    co2eFactor: 1.5,
  },
  {
    code: "METAL-ALU-CAN",
    family: "metal",
    stage: "scrap",
    names: {
      en: "Aluminium cans",
      hi: "एल्युमिनियम कैन",
      kn: "ಅಲ್ಯೂಮಿನಿಯಂ ಕ್ಯಾನ್",
      bn: "অ্যালুমিনিয়ামের ক্যান",
      mr: "ॲल्युमिनियमचे कॅन",
      ta: "அலுமினிய கேன்கள்",
      te: "అల్యూమినియం క్యాన్లు",
      ml: "അലുമിനിയം കാനുകൾ",
      gu: "એલ્યુમિનિયમના કેન",
      pa: "ਐਲੂਮੀਨੀਅਮ ਦੇ ਕੈਨ",
      ur: "ایلومینیم کے کین",
      ar: "علب ألمنيوم",
    },
    floorPaise: 9000,
    fallbackPaise: 11_000,
    co2eFactor: 9,
  },
  {
    code: "METAL-ALU",
    family: "metal",
    stage: "scrap",
    names: {
      en: "Aluminium (utensils)",
      hi: "एल्युमिनियम बर्तन",
      kn: "ಅಲ್ಯೂಮಿನಿಯಂ ಪಾತ್ರೆ",
      bn: "অ্যালুমিনিয়ামের বাসন",
      mr: "ॲल्युमिनियमची भांडी",
      ta: "அலுமினிய பாத்திரங்கள்",
      te: "అల్యూమినియం పాత్రలు",
      ml: "അലുമിനിയം പാത്രങ്ങൾ",
      gu: "એલ્યુમિનિયમનાં વાસણો",
      pa: "ਐਲੂਮੀਨੀਅਮ ਦੇ ਭਾਂਡੇ",
      ur: "ایلومینیم کے برتن",
      ar: "أواني ألمنيوم",
    },
    floorPaise: 11_000,
    fallbackPaise: 13_000,
    co2eFactor: 9,
  },
  {
    code: "METAL-COPPER",
    family: "metal",
    stage: "scrap",
    names: {
      en: "Copper",
      hi: "तांबा",
      kn: "ತಾಮ್ರ",
      bn: "তামা",
      mr: "तांबे",
      ta: "செம்பு",
      te: "రాగి",
      ml: "ചെമ്പ്",
      gu: "તાંબું",
      pa: "ਤਾਂਬਾ",
      ur: "تانبا",
      ar: "نحاس",
    },
    floorPaise: 55_000,
    fallbackPaise: 65_000,
    co2eFactor: 3,
  },
  {
    code: "METAL-BRASS",
    family: "metal",
    stage: "scrap",
    names: {
      en: "Brass",
      hi: "पीतल",
      kn: "ಹಿತ್ತಾಳೆ",
      bn: "পিতল",
      mr: "पितळ",
      ta: "பித்தளை",
      te: "ఇత్తడి",
      ml: "പിച്ചള",
      gu: "પિત્તળ",
      pa: "ਪਿੱਤਲ",
      ur: "پیتل",
      ar: "نحاس أصفر",
    },
    floorPaise: 32_000,
    fallbackPaise: 38_000,
    co2eFactor: 2.5,
  },
  {
    code: "GLASS-BOTTLE",
    family: "glass",
    stage: "scrap",
    names: {
      en: "Glass bottles",
      hi: "काँच की बोतलें",
      kn: "ಗಾಜಿನ ಬಾಟಲಿ",
      bn: "কাচের বোতল",
      mr: "काचेच्या बाटल्या",
      ta: "கண்ணாடி பாட்டில்கள்",
      te: "గాజు సీసాలు",
      ml: "ചില്ലുകുപ്പികൾ",
      gu: "કાચની બોટલો",
      pa: "ਕੱਚ ਦੀਆਂ ਬੋਤਲਾਂ",
      ur: "شیشے کی بوتلیں",
      ar: "زجاجات زجاجية",
    },
    floorPaise: 100,
    fallbackPaise: 200,
    co2eFactor: 0.3,
  },
  {
    code: "EWASTE-SMALL",
    family: "ewaste",
    stage: "scrap",
    names: {
      en: "Small electronics",
      hi: "छोटे इलेक्ट्रॉनिक्स",
      kn: "ಸಣ್ಣ ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್",
      bn: "ছোট ইলেকট্রনিক যন্ত্র",
      mr: "लहान इलेक्ट्रॉनिक उपकरणे",
      ta: "சிறிய மின்னணுச் சாதனங்கள்",
      te: "చిన్న ఎలక్ట్రానిక్ పరికరాలు",
      ml: "ചെറിയ ഇലക്ട്രോണിക് ഉപകരണങ്ങൾ",
      gu: "નાનાં ઇલેક્ટ્રોનિક ઉપકરણો",
      pa: "ਛੋਟੇ ਇਲੈਕਟ੍ਰਾਨਿਕ ਉਪਕਰਨ",
      ur: "چھوٹے الیکٹرانک آلات",
      ar: "أجهزة إلكترونية صغيرة",
    },
    floorPaise: 2000,
    fallbackPaise: 3000,
    co2eFactor: 2,
  },
  {
    code: "EWASTE-PHONE",
    family: "ewaste",
    stage: "scrap",
    names: {
      en: "Old mobile phones",
      hi: "पुराने मोबाइल",
      kn: "ಹಳೆಯ ಮೊಬೈಲ್",
      bn: "পুরোনো মোবাইল ফোন",
      mr: "जुने मोबाइल फोन",
      ta: "பழைய கைப்பேசிகள்",
      te: "పాత మొబైల్ ఫోన్లు",
      ml: "പഴയ മൊബൈൽ ഫോണുകൾ",
      gu: "જૂના મોબાઇલ ફોન",
      pa: "ਪੁਰਾਣੇ ਮੋਬਾਈਲ ਫ਼ੋਨ",
      ur: "پرانے موبائل فون",
      ar: "هواتف محمولة قديمة",
    },
    floorPaise: 10_000,
    fallbackPaise: 15_000,
    co2eFactor: 2,
  },
  {
    code: "EWASTE-CABLE",
    family: "ewaste",
    stage: "scrap",
    names: {
      en: "Wires and cables",
      hi: "तार और केबल",
      kn: "ತಂತಿ ಮತ್ತು ಕೇಬಲ್",
      bn: "তার ও কেবল",
      mr: "तारा आणि केबल",
      ta: "கம்பிகள் மற்றும் கேபிள்கள்",
      te: "తీగలు మరియు కేబుళ్లు",
      ml: "വയറുകളും കേബിളുകളും",
      gu: "તાર અને કેબલ",
      pa: "ਤਾਰਾਂ ਅਤੇ ਕੇਬਲਾਂ",
      ur: "تار اور کیبل",
      ar: "أسلاك وكابلات",
    },
    floorPaise: 8000,
    fallbackPaise: 10_000,
    co2eFactor: 2,
  },
  {
    code: "EWASTE-BATTERY",
    family: "ewaste",
    stage: "scrap",
    names: {
      en: "Lead batteries",
      hi: "बैटरी (इन्वर्टर, गाड़ी)",
      kn: "ಬ್ಯಾಟರಿ (ಇನ್ವರ್ಟರ್, ವಾಹನ)",
      bn: "সিসার ব্যাটারি",
      mr: "शिशाच्या बॅटऱ्या",
      ta: "ஈய மின்கலங்கள்",
      te: "సీసం బ్యాటరీలు",
      ml: "ലെഡ് ബാറ്ററികൾ",
      gu: "સીસાની બેટરીઓ",
      pa: "ਸਿੱਕੇ ਦੀਆਂ ਬੈਟਰੀਆਂ",
      ur: "سیسے کی بیٹریاں",
      ar: "بطاريات رصاص",
    },
    floorPaise: 7000,
    fallbackPaise: 8500,
    co2eFactor: 1,
  },
  {
    code: "OTHER-CLOTHES",
    family: "other",
    stage: "scrap",
    names: {
      en: "Old clothes",
      hi: "पुराने कपड़े",
      kn: "ಹಳೆಯ ಬಟ್ಟೆ",
      bn: "পুরোনো জামাকাপড়",
      mr: "जुने कपडे",
      ta: "பழைய துணிகள்",
      te: "పాత బట్టలు",
      ml: "പഴയ വസ്ത്രങ്ങൾ",
      gu: "જૂનાં કપડાં",
      pa: "ਪੁਰਾਣੇ ਕੱਪੜੇ",
      ur: "پرانے کپڑے",
      ar: "ملابس قديمة",
    },
    floorPaise: 300,
    fallbackPaise: 500,
    co2eFactor: 3,
  },
  // Recycled output: what recyclers sell to manufacturers. Prices are per kg
  // at the factory gate; floor and fallback don't apply to households here.
  {
    code: "RECYCLED-PET-FLAKE",
    family: "plastic",
    stage: "recycled",
    names: {
      en: "Recycled PET flakes",
      hi: "रीसायकल्ड पेट फ़्लेक्स",
      kn: "ಮರುಬಳಕೆ ಪೆಟ್ ಫ್ಲೇಕ್ಸ್",
      bn: "পুনর্ব্যবহৃত PET কুচি",
      mr: "पुनर्प्रक्रिया केलेले PET तुकडे",
      ta: "மறுசுழற்சி செய்யப்பட்ட PET துகள்கள்",
      te: "రీసైకిల్ చేసిన PET తునకలు",
      ml: "പുനഃസംസ്കരിച്ച PET ചീളുകൾ",
      gu: "રિસાયકલ કરેલા PET ટુકડા",
      pa: "ਰੀਸਾਈਕਲ ਕੀਤੇ PET ਟੁਕੜੇ",
      ur: "ری سائیکل شدہ PET کے ٹکڑے",
      ar: "رقائق PET معاد تدويرها",
    },
    floorPaise: 5500,
    fallbackPaise: 6500,
    co2eFactor: 1.5,
  },
  {
    code: "RECYCLED-HDPE-GRANULE",
    family: "plastic",
    stage: "recycled",
    names: {
      en: "Recycled HDPE granules",
      hi: "रीसायकल्ड HDPE दाने",
      kn: "ಮರುಬಳಕೆ HDPE ಕಣಗಳು",
      bn: "পুনর্ব্যবহৃত HDPE দানা",
      mr: "पुनर्प्रक्रिया केलेले HDPE दाणे",
      ta: "மறுசுழற்சி செய்யப்பட்ட HDPE மணிகள்",
      te: "రీసైకిల్ చేసిన HDPE గుళికలు",
      ml: "പുനഃസംസ്കരിച്ച HDPE തരികൾ",
      gu: "રિસાયકલ કરેલા HDPE દાણા",
      pa: "ਰੀਸਾਈਕਲ ਕੀਤੇ HDPE ਦਾਣੇ",
      ur: "ری سائیکل شدہ HDPE کے دانے",
      ar: "حبيبات HDPE معاد تدويرها",
    },
    floorPaise: 6000,
    fallbackPaise: 7000,
    co2eFactor: 1,
  },
  {
    code: "RECYCLED-KRAFT",
    family: "paper",
    stage: "recycled",
    names: {
      en: "Recycled kraft paper",
      hi: "रीसायकल्ड क्राफ़्ट पेपर",
      kn: "ಮರುಬಳಕೆ ಕ್ರಾಫ್ಟ್ ಕಾಗದ",
      bn: "পুনর্ব্যবহৃত ক্রাফট কাগজ",
      mr: "पुनर्प्रक्रिया केलेला क्राफ्ट कागद",
      ta: "மறுசுழற்சி செய்யப்பட்ட கிராஃப்ட் காகிதம்",
      te: "రీసైకిల్ చేసిన క్రాఫ్ట్ కాగితం",
      ml: "പുനഃസംസ്കരിച്ച ക്രാഫ്റ്റ് കടലാസ്",
      gu: "રિસાયકલ કરેલો ક્રાફ્ટ કાગળ",
      pa: "ਰੀਸਾਈਕਲ ਕੀਤਾ ਕਰਾਫ਼ਟ ਕਾਗਜ਼",
      ur: "ری سائیکل شدہ کرافٹ کاغذ",
      ar: "ورق كرافت معاد تدويره",
    },
    floorPaise: 3200,
    fallbackPaise: 3800,
    co2eFactor: 1,
  },
  {
    code: "RECYCLED-ALU-INGOT",
    family: "metal",
    stage: "recycled",
    names: {
      en: "Recycled aluminium ingots",
      hi: "रीसायकल्ड एल्युमिनियम सिल्लियाँ",
      kn: "ಮರುಬಳಕೆ ಅಲ್ಯೂಮಿನಿಯಂ ಗಟ್ಟಿ",
      bn: "পুনর্ব্যবহৃত অ্যালুমিনিয়ামের বাট",
      mr: "पुनर्प्रक्रिया केलेल्या ॲल्युमिनियमच्या लगडी",
      ta: "மறுசுழற்சி செய்யப்பட்ட அலுமினியக் கட்டிகள்",
      te: "రీసైకిల్ చేసిన అల్యూమినియం కడ్డీలు",
      ml: "പുനഃസംസ്കരിച്ച അലുമിനിയം കട്ടികൾ",
      gu: "રિસાયકલ કરેલી એલ્યુમિનિયમની પાટો",
      pa: "ਰੀਸਾਈਕਲ ਕੀਤੀਆਂ ਐਲੂਮੀਨੀਅਮ ਦੀਆਂ ਸਿੱਲੀਆਂ",
      ur: "ری سائیکل شدہ ایلومینیم کی سِلیں",
      ar: "سبائك ألمنيوم معاد تدويرها",
    },
    floorPaise: 18_000,
    fallbackPaise: 21_000,
    co2eFactor: 9,
  },
];

/** How much more each step up the chain typically pays (prototype data). */
export const CHAIN_MARKUP: Record<"kabadiwala" | "yard" | "recycler", number> =
  {
    kabadiwala: 1.25, // a yard pays a kabadiwala ~25% over the household price
    yard: 1.45, // a recycler pays a yard ~45% over it
    recycler: 1.7, // a manufacturer pays a recycler ~70% over it
  };

export function catalogueEntry(code: string): CatalogueEntry | undefined {
  return CATALOGUE.find((entry) => entry.code === code);
}

/** A material's name in a language, falling back to English. */
export function materialName(
  names: Record<string, string> | undefined,
  locale: string,
  code: string,
): string {
  return names?.[locale] ?? names?.en ?? code;
}
